name: Flaky Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn test-compile -pl tsfile -am
      - name: Run without NonDex
        run: mvn -pl tsfile test -Dtest=org.apache.iotdb.tsfile.write.schema.converter.SchemaBuilderTest#testJsonConverter3
      - name: Run with NonDex
        run: mvn -pl tsfile edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.iotdb.tsfile.write.schema.converter.SchemaBuilderTest#testJsonConverter3
